/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as ConhecimentoRouteImport } from './routes/conhecimento'
import { Route as DiretoriaRouteImport } from './routes/diretoria'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ProjetosProjectIdRouteImport } from './routes/projetos_.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoRoute = ConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretoriaRoute = DiretoriaRouteImport.update({
  id: '/diretoria',
  path: '/diretoria',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosProjectIdRoute = ProjetosProjectIdRouteImport.update({
  id: '/projetos_/$projectId',
  path: '/projetos/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/assistente': typeof AssistenteRoute
  '/catalogo': typeof CatalogoRoute
  '/chamados': typeof ChamadosRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/diretoria': typeof DiretoriaRoute
  '/governanca': typeof GovernancaRoute
  '/projetos': typeof ProjetosRoute
  '/recursos': typeof RecursosRoute
  '/api/chat': typeof ApiChatRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/assistente': typeof AssistenteRoute
  '/catalogo': typeof CatalogoRoute
  '/chamados': typeof ChamadosRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/diretoria': typeof DiretoriaRoute
  '/governanca': typeof GovernancaRoute
  '/projetos': typeof ProjetosRoute
  '/recursos': typeof RecursosRoute
  '/api/chat': typeof ApiChatRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/assistente': typeof AssistenteRoute
  '/catalogo': typeof CatalogoRoute
  '/chamados': typeof ChamadosRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/diretoria': typeof DiretoriaRoute
  '/governanca': typeof GovernancaRoute
  '/projetos': typeof ProjetosRoute
  '/recursos': typeof RecursosRoute
  '/api/chat': typeof ApiChatRoute
  '/projetos_/$projectId': typeof ProjetosProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracao'
    | '/assistente'
    | '/catalogo'
    | '/chamados'
    | '/conhecimento'
    | '/diretoria'
    | '/governanca'
    | '/projetos'
    | '/recursos'
    | '/api/chat'
    | '/projetos/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracao'
    | '/assistente'
    | '/catalogo'
    | '/chamados'
    | '/conhecimento'
    | '/diretoria'
    | '/governanca'
    | '/projetos'
    | '/recursos'
    | '/api/chat'
    | '/projetos/$projectId'
  id:
    | '__root__'
    | '/'
    | '/administracao'
    | '/assistente'
    | '/catalogo'
    | '/chamados'
    | '/conhecimento'
    | '/diretoria'
    | '/governanca'
    | '/projetos'
    | '/recursos'
    | '/api/chat'
    | '/projetos_/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracaoRoute: typeof AdministracaoRoute
  AssistenteRoute: typeof AssistenteRoute
  CatalogoRoute: typeof CatalogoRoute
  ChamadosRoute: typeof ChamadosRoute
  ConhecimentoRoute: typeof ConhecimentoRoute
  DiretoriaRoute: typeof DiretoriaRoute
  GovernancaRoute: typeof GovernancaRoute
  ProjetosRoute: typeof ProjetosRoute
  RecursosRoute: typeof RecursosRoute
  ApiChatRoute: typeof ApiChatRoute
  ProjetosProjectIdRoute: typeof ProjetosProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento': {
      id: '/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof ConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretoria': {
      id: '/diretoria'
      path: '/diretoria'
      fullPath: '/diretoria'
      preLoaderRoute: typeof DiretoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos_/$projectId': {
      id: '/projetos_/$projectId'
      path: '/projetos/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof ProjetosProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracaoRoute: AdministracaoRoute,
  AssistenteRoute: AssistenteRoute,
  CatalogoRoute: CatalogoRoute,
  ChamadosRoute: ChamadosRoute,
  ConhecimentoRoute: ConhecimentoRoute,
  DiretoriaRoute: DiretoriaRoute,
  GovernancaRoute: GovernancaRoute,
  ProjetosRoute: ProjetosRoute,
  RecursosRoute: RecursosRoute,
  ApiChatRoute: ApiChatRoute,
  ProjetosProjectIdRoute: ProjetosProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
