/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AfiliadoRouteImport } from './routes/afiliado'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as ConhecimentoRouteImport } from './routes/conhecimento'
import { Route as ContratarRouteImport } from './routes/contratar'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as DiretoriaRouteImport } from './routes/diretoria'
import { Route as GovernancaRouteImport } from './routes/governanca'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PermissoesRouteImport } from './routes/permissoes'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as AdministracaoIndexRouteImport } from './routes/administracao.index'
import { Route as AdministracaoCalendarioRouteImport } from './routes/administracao.calendario'
import { Route as AdministracaoFornecedoresRouteImport } from './routes/administracao.fornecedores'
import { Route as AdministracaoNotificacoesRouteImport } from './routes/administracao.notificacoes'
import { Route as AdministracaoSistemasRouteImport } from './routes/administracao.sistemas'
import { Route as AdministracaoUsuariosRouteImport } from './routes/administracao.usuarios'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiRotinasRouteImport } from './routes/api/rotinas'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as IndicacaoCodigoRouteImport } from './routes/indicacao.$codigo'
import { Route as PlataformaComercialRouteImport } from './routes/plataforma.comercial'
import { Route as PlataformaEmpresasRouteImport } from './routes/plataforma.empresas'
import { Route as ProjetosProjectIdRouteImport } from './routes/projetos_.$projectId'
import { Route as ApiWebhooksAsaasRouteImport } from './routes/api/webhooks/asaas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoRoute = AfiliadoRouteImport.update({
  id: '/afiliado',
  path: '/afiliado',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoRoute = ConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratarRoute = ContratarRouteImport.update({
  id: '/contratar',
  path: '/contratar',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretoriaRoute = DiretoriaRouteImport.update({
  id: '/diretoria',
  path: '/diretoria',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernancaRoute = GovernancaRouteImport.update({
  id: '/governanca',
  path: '/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissoesRoute = PermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoIndexRoute = AdministracaoIndexRouteImport.update({
  id: '/administracao/',
  path: '/administracao/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoCalendarioRoute = AdministracaoCalendarioRouteImport.update({
  id: '/administracao/calendario',
  path: '/administracao/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoFornecedoresRoute =
  AdministracaoFornecedoresRouteImport.update({
    id: '/administracao/fornecedores',
    path: '/administracao/fornecedores',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministracaoNotificacoesRoute =
  AdministracaoNotificacoesRouteImport.update({
    id: '/administracao/notificacoes',
    path: '/administracao/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministracaoSistemasRoute = AdministracaoSistemasRouteImport.update({
  id: '/administracao/sistemas',
  path: '/administracao/sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoUsuariosRoute = AdministracaoUsuariosRouteImport.update({
  id: '/administracao/usuarios',
  path: '/administracao/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRotinasRoute = ApiRotinasRouteImport.update({
  id: '/api/rotinas',
  path: '/api/rotinas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacaoCodigoRoute = IndicacaoCodigoRouteImport.update({
  id: '/indicacao/$codigo',
  path: '/indicacao/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaComercialRoute = PlataformaComercialRouteImport.update({
  id: '/plataforma/comercial',
  path: '/plataforma/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaEmpresasRoute = PlataformaEmpresasRouteImport.update({
  id: '/plataforma/empresas',
  path: '/plataforma/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosProjectIdRoute = ProjetosProjectIdRouteImport.update({
  id: '/projetos_/$projectId',
  path: '/projetos/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksAsaasRoute = ApiWebhooksAsaasRouteImport.update({
  id: '/api/webhooks/asaas',
  path: '/api/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afiliado': typeof AfiliadoRoute
  '/assinatura': typeof AssinaturaRoute
  '/assistente': typeof AssistenteRoute
  '/backlog': typeof BacklogRoute
  '/catalogo': typeof CatalogoRoute
  '/chamados': typeof ChamadosRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/contratar': typeof ContratarRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/diretoria': typeof DiretoriaRoute
  '/governanca': typeof GovernancaRoute
  '/login': typeof LoginRoute
  '/permissoes': typeof PermissoesRoute
  '/projetos': typeof ProjetosRoute
  '/recursos': typeof RecursosRoute
  '/administracao/calendario': typeof AdministracaoCalendarioRoute
  '/administracao/fornecedores': typeof AdministracaoFornecedoresRoute
  '/administracao/notificacoes': typeof AdministracaoNotificacoesRoute
  '/administracao/sistemas': typeof AdministracaoSistemasRoute
  '/administracao/usuarios': typeof AdministracaoUsuariosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/rotinas': typeof ApiRotinasRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/indicacao/$codigo': typeof IndicacaoCodigoRoute
  '/plataforma/comercial': typeof PlataformaComercialRoute
  '/plataforma/empresas': typeof PlataformaEmpresasRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/administracao/': typeof AdministracaoIndexRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliado': typeof AfiliadoRoute
  '/assinatura': typeof AssinaturaRoute
  '/assistente': typeof AssistenteRoute
  '/backlog': typeof BacklogRoute
  '/catalogo': typeof CatalogoRoute
  '/chamados': typeof ChamadosRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/contratar': typeof ContratarRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/diretoria': typeof DiretoriaRoute
  '/governanca': typeof GovernancaRoute
  '/login': typeof LoginRoute
  '/permissoes': typeof PermissoesRoute
  '/projetos': typeof ProjetosRoute
  '/recursos': typeof RecursosRoute
  '/administracao/calendario': typeof AdministracaoCalendarioRoute
  '/administracao/fornecedores': typeof AdministracaoFornecedoresRoute
  '/administracao/notificacoes': typeof AdministracaoNotificacoesRoute
  '/administracao/sistemas': typeof AdministracaoSistemasRoute
  '/administracao/usuarios': typeof AdministracaoUsuariosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/rotinas': typeof ApiRotinasRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/indicacao/$codigo': typeof IndicacaoCodigoRoute
  '/plataforma/comercial': typeof PlataformaComercialRoute
  '/plataforma/empresas': typeof PlataformaEmpresasRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/administracao': typeof AdministracaoIndexRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afiliado': typeof AfiliadoRoute
  '/assinatura': typeof AssinaturaRoute
  '/assistente': typeof AssistenteRoute
  '/backlog': typeof BacklogRoute
  '/catalogo': typeof CatalogoRoute
  '/chamados': typeof ChamadosRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/contratar': typeof ContratarRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/diretoria': typeof DiretoriaRoute
  '/governanca': typeof GovernancaRoute
  '/login': typeof LoginRoute
  '/permissoes': typeof PermissoesRoute
  '/projetos': typeof ProjetosRoute
  '/recursos': typeof RecursosRoute
  '/administracao/calendario': typeof AdministracaoCalendarioRoute
  '/administracao/fornecedores': typeof AdministracaoFornecedoresRoute
  '/administracao/notificacoes': typeof AdministracaoNotificacoesRoute
  '/administracao/sistemas': typeof AdministracaoSistemasRoute
  '/administracao/usuarios': typeof AdministracaoUsuariosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/rotinas': typeof ApiRotinasRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/indicacao/$codigo': typeof IndicacaoCodigoRoute
  '/plataforma/comercial': typeof PlataformaComercialRoute
  '/plataforma/empresas': typeof PlataformaEmpresasRoute
  '/projetos_/$projectId': typeof ProjetosProjectIdRoute
  '/administracao/': typeof AdministracaoIndexRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afiliado'
    | '/assinatura'
    | '/assistente'
    | '/backlog'
    | '/catalogo'
    | '/chamados'
    | '/conhecimento'
    | '/contratar'
    | '/definir-senha'
    | '/diretoria'
    | '/governanca'
    | '/login'
    | '/permissoes'
    | '/projetos'
    | '/recursos'
    | '/administracao/calendario'
    | '/administracao/fornecedores'
    | '/administracao/notificacoes'
    | '/administracao/sistemas'
    | '/administracao/usuarios'
    | '/api/chat'
    | '/api/rotinas'
    | '/auth/confirm'
    | '/indicacao/$codigo'
    | '/plataforma/comercial'
    | '/plataforma/empresas'
    | '/projetos/$projectId'
    | '/administracao/'
    | '/api/webhooks/asaas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliado'
    | '/assinatura'
    | '/assistente'
    | '/backlog'
    | '/catalogo'
    | '/chamados'
    | '/conhecimento'
    | '/contratar'
    | '/definir-senha'
    | '/diretoria'
    | '/governanca'
    | '/login'
    | '/permissoes'
    | '/projetos'
    | '/recursos'
    | '/administracao/calendario'
    | '/administracao/fornecedores'
    | '/administracao/notificacoes'
    | '/administracao/sistemas'
    | '/administracao/usuarios'
    | '/api/chat'
    | '/api/rotinas'
    | '/auth/confirm'
    | '/indicacao/$codigo'
    | '/plataforma/comercial'
    | '/plataforma/empresas'
    | '/projetos/$projectId'
    | '/administracao'
    | '/api/webhooks/asaas'
  id:
    | '__root__'
    | '/'
    | '/afiliado'
    | '/assinatura'
    | '/assistente'
    | '/backlog'
    | '/catalogo'
    | '/chamados'
    | '/conhecimento'
    | '/contratar'
    | '/definir-senha'
    | '/diretoria'
    | '/governanca'
    | '/login'
    | '/permissoes'
    | '/projetos'
    | '/recursos'
    | '/administracao/calendario'
    | '/administracao/fornecedores'
    | '/administracao/notificacoes'
    | '/administracao/sistemas'
    | '/administracao/usuarios'
    | '/api/chat'
    | '/api/rotinas'
    | '/auth/confirm'
    | '/indicacao/$codigo'
    | '/plataforma/comercial'
    | '/plataforma/empresas'
    | '/projetos_/$projectId'
    | '/administracao/'
    | '/api/webhooks/asaas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfiliadoRoute: typeof AfiliadoRoute
  AssinaturaRoute: typeof AssinaturaRoute
  AssistenteRoute: typeof AssistenteRoute
  BacklogRoute: typeof BacklogRoute
  CatalogoRoute: typeof CatalogoRoute
  ChamadosRoute: typeof ChamadosRoute
  ConhecimentoRoute: typeof ConhecimentoRoute
  ContratarRoute: typeof ContratarRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  DiretoriaRoute: typeof DiretoriaRoute
  GovernancaRoute: typeof GovernancaRoute
  LoginRoute: typeof LoginRoute
  PermissoesRoute: typeof PermissoesRoute
  ProjetosRoute: typeof ProjetosRoute
  RecursosRoute: typeof RecursosRoute
  AdministracaoCalendarioRoute: typeof AdministracaoCalendarioRoute
  AdministracaoFornecedoresRoute: typeof AdministracaoFornecedoresRoute
  AdministracaoNotificacoesRoute: typeof AdministracaoNotificacoesRoute
  AdministracaoSistemasRoute: typeof AdministracaoSistemasRoute
  AdministracaoUsuariosRoute: typeof AdministracaoUsuariosRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiRotinasRoute: typeof ApiRotinasRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  IndicacaoCodigoRoute: typeof IndicacaoCodigoRoute
  PlataformaComercialRoute: typeof PlataformaComercialRoute
  PlataformaEmpresasRoute: typeof PlataformaEmpresasRoute
  ProjetosProjectIdRoute: typeof ProjetosProjectIdRoute
  AdministracaoIndexRoute: typeof AdministracaoIndexRoute
  ApiWebhooksAsaasRoute: typeof ApiWebhooksAsaasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado': {
      id: '/afiliado'
      path: '/afiliado'
      fullPath: '/afiliado'
      preLoaderRoute: typeof AfiliadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento': {
      id: '/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof ConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratar': {
      id: '/contratar'
      path: '/contratar'
      fullPath: '/contratar'
      preLoaderRoute: typeof ContratarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretoria': {
      id: '/diretoria'
      path: '/diretoria'
      fullPath: '/diretoria'
      preLoaderRoute: typeof DiretoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governanca': {
      id: '/governanca'
      path: '/governanca'
      fullPath: '/governanca'
      preLoaderRoute: typeof GovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissoes': {
      id: '/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof PermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao/': {
      id: '/administracao/'
      path: '/administracao'
      fullPath: '/administracao/'
      preLoaderRoute: typeof AdministracaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao/calendario': {
      id: '/administracao/calendario'
      path: '/administracao/calendario'
      fullPath: '/administracao/calendario'
      preLoaderRoute: typeof AdministracaoCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao/fornecedores': {
      id: '/administracao/fornecedores'
      path: '/administracao/fornecedores'
      fullPath: '/administracao/fornecedores'
      preLoaderRoute: typeof AdministracaoFornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao/notificacoes': {
      id: '/administracao/notificacoes'
      path: '/administracao/notificacoes'
      fullPath: '/administracao/notificacoes'
      preLoaderRoute: typeof AdministracaoNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao/sistemas': {
      id: '/administracao/sistemas'
      path: '/administracao/sistemas'
      fullPath: '/administracao/sistemas'
      preLoaderRoute: typeof AdministracaoSistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao/usuarios': {
      id: '/administracao/usuarios'
      path: '/administracao/usuarios'
      fullPath: '/administracao/usuarios'
      preLoaderRoute: typeof AdministracaoUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rotinas': {
      id: '/api/rotinas'
      path: '/api/rotinas'
      fullPath: '/api/rotinas'
      preLoaderRoute: typeof ApiRotinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacao/$codigo': {
      id: '/indicacao/$codigo'
      path: '/indicacao/$codigo'
      fullPath: '/indicacao/$codigo'
      preLoaderRoute: typeof IndicacaoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma/comercial': {
      id: '/plataforma/comercial'
      path: '/plataforma/comercial'
      fullPath: '/plataforma/comercial'
      preLoaderRoute: typeof PlataformaComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma/empresas': {
      id: '/plataforma/empresas'
      path: '/plataforma/empresas'
      fullPath: '/plataforma/empresas'
      preLoaderRoute: typeof PlataformaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos_/$projectId': {
      id: '/projetos_/$projectId'
      path: '/projetos/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof ProjetosProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/asaas': {
      id: '/api/webhooks/asaas'
      path: '/api/webhooks/asaas'
      fullPath: '/api/webhooks/asaas'
      preLoaderRoute: typeof ApiWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfiliadoRoute: AfiliadoRoute,
  AssinaturaRoute: AssinaturaRoute,
  AssistenteRoute: AssistenteRoute,
  BacklogRoute: BacklogRoute,
  CatalogoRoute: CatalogoRoute,
  ChamadosRoute: ChamadosRoute,
  ConhecimentoRoute: ConhecimentoRoute,
  ContratarRoute: ContratarRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  DiretoriaRoute: DiretoriaRoute,
  GovernancaRoute: GovernancaRoute,
  LoginRoute: LoginRoute,
  PermissoesRoute: PermissoesRoute,
  ProjetosRoute: ProjetosRoute,
  RecursosRoute: RecursosRoute,
  AdministracaoCalendarioRoute: AdministracaoCalendarioRoute,
  AdministracaoFornecedoresRoute: AdministracaoFornecedoresRoute,
  AdministracaoNotificacoesRoute: AdministracaoNotificacoesRoute,
  AdministracaoSistemasRoute: AdministracaoSistemasRoute,
  AdministracaoUsuariosRoute: AdministracaoUsuariosRoute,
  ApiChatRoute: ApiChatRoute,
  ApiRotinasRoute: ApiRotinasRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  IndicacaoCodigoRoute: IndicacaoCodigoRoute,
  PlataformaComercialRoute: PlataformaComercialRoute,
  PlataformaEmpresasRoute: PlataformaEmpresasRoute,
  ProjetosProjectIdRoute: ProjetosProjectIdRoute,
  AdministracaoIndexRoute: AdministracaoIndexRoute,
  ApiWebhooksAsaasRoute: ApiWebhooksAsaasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
