-- =====================================================================
-- YpperConnect - schema Postgres (migrado do Oracle 19c)
-- Booleanos viram BOOLEAN, TIMESTAMP vira TIMESTAMPTZ, CLOB vira TEXT.
-- Acesso exclusivo do servidor da aplicacao (service_role).
-- =====================================================================

-- 1. Listas administraveis -------------------------------------------
CREATE TABLE public.equipes (
  id    text PRIMARY KEY,
  nome  text NOT NULL UNIQUE,
  ativo boolean NOT NULL DEFAULT true
);

CREATE TABLE public.categorias (
  id     text PRIMARY KEY,
  nome   text NOT NULL,
  escopo text NOT NULL CHECK (escopo IN ('chamado','servico','artigo','sistema')),
  ativo  boolean NOT NULL DEFAULT true,
  UNIQUE (escopo, nome)
);

-- 2. Identidade e autorizacao ----------------------------------------
CREATE TABLE public.perfis_acesso (
  id        text PRIMARY KEY,
  nome      text NOT NULL UNIQUE,
  descricao text,
  sistema   boolean NOT NULL DEFAULT false,
  ativo     boolean NOT NULL DEFAULT true
);

CREATE TABLE public.usuarios (
  id              text PRIMARY KEY,
  ad_object_id    text UNIQUE,
  nome            text NOT NULL,
  email           text NOT NULL,
  login           text NOT NULL UNIQUE,
  departamento    text,
  equipe_id       text REFERENCES public.equipes (id),
  perfil_id       text REFERENCES public.perfis_acesso (id),
  origem          text NOT NULL DEFAULT 'manual' CHECK (origem IN ('ad','manual')),
  admin           boolean NOT NULL DEFAULT false,
  ativo           boolean NOT NULL DEFAULT true,
  sincronizado_em timestamptz,
  criado_em       timestamptz NOT NULL DEFAULT now(),
  atualizado_em   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_usuarios_email ON public.usuarios (email);
CREATE INDEX ix_usuarios_ativo ON public.usuarios (ativo);
CREATE INDEX ix_usuarios_equipe ON public.usuarios (equipe_id);

CREATE TABLE public.perfil_modulos (
  perfil_id  text NOT NULL REFERENCES public.perfis_acesso (id) ON DELETE CASCADE,
  modulo_key text NOT NULL,
  PRIMARY KEY (perfil_id, modulo_key)
);

CREATE TABLE public.perfil_features (
  perfil_id   text NOT NULL REFERENCES public.perfis_acesso (id) ON DELETE CASCADE,
  feature_key text NOT NULL,
  PRIMARY KEY (perfil_id, feature_key)
);

-- 3. Catalogo, sistemas e conhecimento -------------------------------
CREATE TABLE public.servicos (
  id            text PRIMARY KEY,
  nome          text NOT NULL,
  categoria_id  text REFERENCES public.categorias (id),
  descricao     text,
  tipo_padrao   text NOT NULL CHECK (tipo_padrao IN ('incidente','requisicao','melhoria','problema','tarefa')),
  sla_horas     integer NOT NULL CHECK (sla_horas > 0),
  equipe_id     text REFERENCES public.equipes (id),
  gerado_por_ia boolean NOT NULL DEFAULT false,
  ativo         boolean NOT NULL DEFAULT true,
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_servicos_categoria ON public.servicos (categoria_id);
CREATE INDEX ix_servicos_ativo ON public.servicos (ativo);

CREATE TABLE public.sistemas (
  id             text PRIMARY KEY,
  nome           text NOT NULL UNIQUE,
  descricao      text,
  categoria_id   text REFERENCES public.categorias (id),
  responsavel_id text REFERENCES public.usuarios (id),
  atribuicao_id  text REFERENCES public.usuarios (id),
  equipe_id      text REFERENCES public.equipes (id),
  criticidade    text NOT NULL CHECK (criticidade IN ('alta','media','baixa')),
  ativo          boolean NOT NULL DEFAULT true
);
CREATE INDEX ix_sistemas_responsavel ON public.sistemas (responsavel_id);
CREATE INDEX ix_sistemas_equipe ON public.sistemas (equipe_id);

CREATE TABLE public.artigos (
  id            text PRIMARY KEY,
  titulo        text NOT NULL,
  categoria_id  text REFERENCES public.categorias (id),
  resumo        text,
  conteudo      text NOT NULL,
  status        text NOT NULL DEFAULT 'rascunho' CHECK (status IN ('publicado','revisar','rascunho')),
  visualizacoes integer NOT NULL DEFAULT 0,
  gerado_por_ia boolean NOT NULL DEFAULT false,
  autor_id      text REFERENCES public.usuarios (id),
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_artigos_status ON public.artigos (status);
CREATE INDEX ix_artigos_categoria ON public.artigos (categoria_id);

-- 4. Chamados ---------------------------------------------------------
CREATE TABLE public.chamados (
  id                     text PRIMARY KEY,
  numero                 bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) UNIQUE,
  prefixo                text NOT NULL DEFAULT 'CHM',
  codigo                 text GENERATED ALWAYS AS (prefixo || '-' || numero::text) STORED,
  titulo                 text NOT NULL,
  descricao              text NOT NULL,
  tipo                   text NOT NULL CHECK (tipo IN ('incidente','requisicao','melhoria','problema','tarefa')),
  categoria_id           text REFERENCES public.categorias (id),
  servico_id             text REFERENCES public.servicos (id),
  sistema_id             text REFERENCES public.sistemas (id),
  impacto                text NOT NULL CHECK (impacto IN ('alto','medio','baixo')),
  urgencia               text NOT NULL CHECK (urgencia IN ('alta','media','baixa')),
  prioridade             text NOT NULL CHECK (prioridade IN ('P1','P2','P3','P4')),
  status                 text NOT NULL DEFAULT 'novo' CHECK (status IN ('novo','triagem','em_andamento','aguardando','resolvido','fechado')),
  solicitante_id         text NOT NULL REFERENCES public.usuarios (id),
  responsavel_id         text REFERENCES public.usuarios (id),
  equipe_id              text REFERENCES public.equipes (id),
  origem                 text NOT NULL CHECK (origem IN ('portal','ia','email','telefone')),
  problema_vinculado_id  text REFERENCES public.chamados (id),
  descricao_encerramento text,
  criado_em              timestamptz NOT NULL DEFAULT now(),
  atualizado_em          timestamptz NOT NULL DEFAULT now(),
  prazo_resposta         timestamptz,
  prazo_sla              timestamptz NOT NULL,
  respondido_em          timestamptz,
  resolvido_em           timestamptz,
  fechado_em             timestamptz
);
CREATE UNIQUE INDEX ux_chamados_codigo ON public.chamados (codigo);
CREATE INDEX ix_chamados_status_prazo ON public.chamados (status, prazo_sla);
CREATE INDEX ix_chamados_responsavel ON public.chamados (responsavel_id, status);
CREATE INDEX ix_chamados_solicitante ON public.chamados (solicitante_id, criado_em);
CREATE INDEX ix_chamados_servico ON public.chamados (servico_id);
CREATE INDEX ix_chamados_sistema ON public.chamados (sistema_id);
CREATE INDEX ix_chamados_criado ON public.chamados (criado_em);
CREATE INDEX ix_chamados_equipe_status ON public.chamados (equipe_id, status);

CREATE TABLE public.chamado_interacoes (
  id         text PRIMARY KEY,
  chamado_id text NOT NULL REFERENCES public.chamados (id) ON DELETE CASCADE,
  autor_id   text REFERENCES public.usuarios (id),
  tipo       text NOT NULL CHECK (tipo IN ('comentario','nota_interna','email')),
  corpo      text NOT NULL,
  criado_em  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_interacoes_chamado ON public.chamado_interacoes (chamado_id, criado_em);

CREATE TABLE public.chamado_historico (
  id             text PRIMARY KEY,
  chamado_id     text NOT NULL REFERENCES public.chamados (id) ON DELETE CASCADE,
  autor_id       text REFERENCES public.usuarios (id),
  campo          text NOT NULL,
  valor_anterior text,
  valor_novo     text,
  criado_em      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_historico_chamado ON public.chamado_historico (chamado_id, criado_em);
CREATE INDEX ix_historico_campo ON public.chamado_historico (campo, criado_em);

-- 5. Recursos ---------------------------------------------------------
CREATE TABLE public.recursos (
  id                       text PRIMARY KEY,
  usuario_id               text UNIQUE REFERENCES public.usuarios (id),
  nome                     text NOT NULL,
  papel                    text,
  equipe_id                text REFERENCES public.equipes (id),
  horas_dia                double precision NOT NULL DEFAULT 8 CHECK (horas_dia > 0 AND horas_dia <= 24),
  disponibilidade_projetos integer NOT NULL DEFAULT 50 CHECK (disponibilidade_projetos BETWEEN 0 AND 100),
  ativo                    boolean NOT NULL DEFAULT true
);
CREATE INDEX ix_recursos_equipe ON public.recursos (equipe_id);

-- 6. Projetos ---------------------------------------------------------
CREATE TABLE public.projetos (
  id            text PRIMARY KEY,
  nome          text NOT NULL,
  objetivo      text,
  sponsor_id    text REFERENCES public.usuarios (id),
  gerente_id    text REFERENCES public.usuarios (id),
  status        text NOT NULL DEFAULT 'planejamento' CHECK (status IN ('planejamento','execucao','paralisado','cancelado','concluido')),
  inicio        date NOT NULL,
  fim           date NOT NULL CHECK (fim >= inicio),
  criado_em     timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_projetos_status ON public.projetos (status);
CREATE INDEX ix_projetos_gerente ON public.projetos (gerente_id);

CREATE TABLE public.projeto_tarefas (
  id              text PRIMARY KEY,
  projeto_id      text NOT NULL REFERENCES public.projetos (id) ON DELETE CASCADE,
  pai_id          text REFERENCES public.projeto_tarefas (id) ON DELETE CASCADE,
  nome            text NOT NULL,
  atividade       text,
  inicio          date NOT NULL,
  fim             date NOT NULL,
  progresso       integer NOT NULL DEFAULT 0 CHECK (progresso BETWEEN 0 AND 100),
  quadro          text NOT NULL DEFAULT 'backlog' CHECK (quadro IN ('backlog','todo','doing','done')),
  marco           boolean NOT NULL DEFAULT false,
  duracao         double precision,
  duracao_unidade text CHECK (duracao_unidade IS NULL OR duracao_unidade IN ('dias','horas')),
  alocacao_pct    integer CHECK (alocacao_pct IS NULL OR alocacao_pct BETWEEN 0 AND 100),
  ordem           integer NOT NULL DEFAULT 0,
  concluido_em    timestamptz,
  CHECK (fim >= inicio),
  CHECK (pai_id IS NULL OR pai_id <> id)
);
CREATE INDEX ix_tarefas_projeto ON public.projeto_tarefas (projeto_id, ordem);
CREATE INDEX ix_tarefas_quadro ON public.projeto_tarefas (projeto_id, quadro);
CREATE INDEX ix_tarefas_pai ON public.projeto_tarefas (pai_id);

CREATE TABLE public.tarefa_responsaveis (
  tarefa_id  text NOT NULL REFERENCES public.projeto_tarefas (id) ON DELETE CASCADE,
  recurso_id text NOT NULL REFERENCES public.recursos (id),
  principal  boolean NOT NULL DEFAULT false,
  PRIMARY KEY (tarefa_id, recurso_id)
);
CREATE INDEX ix_tresp_recurso ON public.tarefa_responsaveis (recurso_id);

CREATE TABLE public.tarefa_predecessoras (
  tarefa_id       text NOT NULL REFERENCES public.projeto_tarefas (id) ON DELETE CASCADE,
  predecessora_id text NOT NULL REFERENCES public.projeto_tarefas (id),
  PRIMARY KEY (tarefa_id, predecessora_id),
  CHECK (tarefa_id <> predecessora_id)
);
CREATE INDEX ix_tpred_pred ON public.tarefa_predecessoras (predecessora_id);

CREATE TABLE public.projeto_atualizacoes (
  id                text PRIMARY KEY,
  projeto_id        text NOT NULL REFERENCES public.projetos (id) ON DELETE CASCADE,
  autor_id          text REFERENCES public.usuarios (id),
  data_ref          date NOT NULL,
  descricao         text,
  ultimas_entregas  text,
  proximas_entregas text,
  criado_em         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_patual_projeto ON public.projeto_atualizacoes (projeto_id, data_ref);

CREATE TABLE public.projeto_riscos (
  id            text PRIMARY KEY,
  projeto_id    text NOT NULL REFERENCES public.projetos (id) ON DELETE CASCADE,
  descricao     text NOT NULL,
  probabilidade text NOT NULL CHECK (probabilidade IN ('alta','media','baixa')),
  impacto       text NOT NULL CHECK (impacto IN ('alto','medio','baixo')),
  mitigacao     text,
  status        text NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto','monitorado','mitigado')),
  criado_em     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_riscos_projeto ON public.projeto_riscos (projeto_id, status);

CREATE TABLE public.projeto_atencoes (
  id                     text PRIMARY KEY,
  projeto_id             text NOT NULL REFERENCES public.projetos (id) ON DELETE CASCADE,
  titulo                 text NOT NULL,
  descricao              text,
  decisao_necessaria     text,
  responsavel_decisao_id text REFERENCES public.usuarios (id),
  status                 text NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto','resolvido')),
  criado_em              timestamptz NOT NULL DEFAULT now(),
  resolvido_em           timestamptz
);
CREATE INDEX ix_atencoes_projeto ON public.projeto_atencoes (projeto_id, status);

CREATE TABLE public.projeto_baselines (
  id         text PRIMARY KEY,
  projeto_id text NOT NULL REFERENCES public.projetos (id) ON DELETE CASCADE,
  versao     integer NOT NULL,
  descricao  text,
  autor_id   text REFERENCES public.usuarios (id),
  criado_em  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (projeto_id, versao)
);

CREATE TABLE public.baseline_tarefas (
  baseline_id text NOT NULL REFERENCES public.projeto_baselines (id) ON DELETE CASCADE,
  tarefa_id   text NOT NULL,
  nome        text NOT NULL,
  inicio      date NOT NULL,
  fim         date NOT NULL,
  PRIMARY KEY (baseline_id, tarefa_id)
);

-- 7. Notificacoes ------------------------------------------------------
CREATE TABLE public.notificacoes (
  id                 text PRIMARY KEY,
  tipo               text NOT NULL CHECK (tipo IN ('chamado_status','chamado_criado','projeto_lembrete')),
  destinatario_id    text REFERENCES public.usuarios (id),
  destinatario_email text NOT NULL,
  assunto            text NOT NULL,
  corpo              text,
  referencia_tipo    text CHECK (referencia_tipo IS NULL OR referencia_tipo IN ('chamado','projeto')),
  referencia_id      text,
  status             text NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','enviado','erro')),
  tentativas         integer NOT NULL DEFAULT 0,
  erro               text,
  criado_em          timestamptz NOT NULL DEFAULT now(),
  enviado_em         timestamptz
);
CREATE INDEX ix_notif_status ON public.notificacoes (status, criado_em);

-- 8. Calendario --------------------------------------------------------
CREATE TABLE public.expediente (
  id         text PRIMARY KEY,
  dia_semana integer NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
  minuto_ini integer NOT NULL CHECK (minuto_ini BETWEEN 0 AND 1440),
  minuto_fim integer NOT NULL CHECK (minuto_fim BETWEEN 0 AND 1440),
  ativo      boolean NOT NULL DEFAULT true,
  UNIQUE (dia_semana, minuto_ini),
  CHECK (minuto_fim > minuto_ini)
);

CREATE TABLE public.feriados (
  id           text PRIMARY KEY,
  data_feriado date NOT NULL UNIQUE,
  descricao    text NOT NULL,
  tipo         text NOT NULL DEFAULT 'nacional' CHECK (tipo IN ('nacional','estadual','municipal','facultativo')),
  recorrente   boolean NOT NULL DEFAULT false,
  ativo        boolean NOT NULL DEFAULT true,
  mes          integer GENERATED ALWAYS AS (EXTRACT(MONTH FROM data_feriado)::integer) STORED,
  dia          integer GENERATED ALWAYS AS (EXTRACT(DAY FROM data_feriado)::integer) STORED
);
CREATE INDEX ix_feriados_data ON public.feriados (data_feriado, ativo);
CREATE INDEX ix_feriados_recorrente ON public.feriados (recorrente, mes, dia, ativo);

-- 9. Acesso: somente o servidor da aplicacao --------------------------
DO $$
DECLARE t text;
BEGIN
  FOR t IN
    SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relkind = 'r'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
  END LOOP;
END;
$$;

-- 10. Carga inicial ----------------------------------------------------
INSERT INTO public.perfis_acesso (id, nome, descricao, sistema) VALUES
  ('PRF-ADMIN', 'Administrador de TI', 'Acesso total ao sistema, incluindo cadastros administrativos e perfis de acesso.', true),
  ('PRF-AGENTE', 'Analista de TI', 'Atende chamados, gerencia problemas, projetos e a base de conhecimento.', true),
  ('PRF-GESTOR', 'Gestor / Diretoria', 'Visualiza indicadores executivos de projetos e atendimento.', true),
  ('PRF-USUARIO', 'Usuário final', 'Abre chamados pelo catálogo e consulta a base de conhecimento. Não cria problemas.', true);

INSERT INTO public.perfil_modulos (perfil_id, modulo_key) VALUES
  ('PRF-ADMIN','/'),('PRF-ADMIN','/chamados'),('PRF-ADMIN','/catalogo'),('PRF-ADMIN','/conhecimento'),
  ('PRF-ADMIN','/assistente'),('PRF-ADMIN','/projetos'),('PRF-ADMIN','/recursos'),('PRF-ADMIN','/diretoria'),
  ('PRF-ADMIN','/governanca'),('PRF-ADMIN','/administracao'),('PRF-ADMIN','/permissoes'),
  ('PRF-AGENTE','/'),('PRF-AGENTE','/chamados'),('PRF-AGENTE','/catalogo'),('PRF-AGENTE','/conhecimento'),
  ('PRF-AGENTE','/assistente'),('PRF-AGENTE','/projetos'),('PRF-AGENTE','/recursos'),('PRF-AGENTE','/governanca'),
  ('PRF-GESTOR','/'),('PRF-GESTOR','/chamados'),('PRF-GESTOR','/conhecimento'),('PRF-GESTOR','/projetos'),
  ('PRF-GESTOR','/recursos'),('PRF-GESTOR','/diretoria'),('PRF-GESTOR','/governanca'),
  ('PRF-USUARIO','/'),('PRF-USUARIO','/chamados'),('PRF-USUARIO','/catalogo'),('PRF-USUARIO','/conhecimento'),
  ('PRF-USUARIO','/assistente');

INSERT INTO public.perfil_features (perfil_id, feature_key) VALUES
  ('PRF-ADMIN','chamado.criar'),('PRF-ADMIN','chamado.editar'),('PRF-ADMIN','chamado.problema'),
  ('PRF-ADMIN','conhecimento.editar'),('PRF-ADMIN','catalogo.editar'),('PRF-ADMIN','projeto.criar'),
  ('PRF-ADMIN','projeto.editar'),('PRF-ADMIN','recurso.editar'),('PRF-ADMIN','admin.usuarios'),
  ('PRF-ADMIN','admin.sistemas'),('PRF-ADMIN','admin.permissoes'),
  ('PRF-AGENTE','chamado.criar'),('PRF-AGENTE','chamado.editar'),('PRF-AGENTE','chamado.problema'),
  ('PRF-AGENTE','conhecimento.editar'),('PRF-AGENTE','projeto.criar'),('PRF-AGENTE','projeto.editar'),
  ('PRF-AGENTE','recurso.editar'),
  ('PRF-GESTOR','chamado.criar'),
  ('PRF-USUARIO','chamado.criar');

INSERT INTO public.equipes (id, nome) VALUES
  ('EQP-SDK','Service Desk'),('EQP-INF','Infraestrutura'),('EQP-SIS','Sistemas');

INSERT INTO public.categorias (id, nome, escopo) VALUES
  ('CAT-SVC-01','Acessos','servico'),('CAT-SVC-02','Infraestrutura','servico'),('CAT-SVC-03','Sistemas','servico'),
  ('CAT-CHA-01','Acessos','chamado'),('CAT-CHA-02','Infraestrutura','chamado'),('CAT-CHA-03','Sistemas','chamado'),
  ('CAT-SIS-01','Aplicações','sistema'),('CAT-SIS-02','Infraestrutura','sistema'),
  ('CAT-ART-01','Procedimentos','artigo'),('CAT-ART-02','Soluções','artigo');

INSERT INTO public.usuarios (id, nome, email, login, departamento, equipe_id, perfil_id, origem, admin, ativo)
VALUES ('USR-ADMIN','Breno Ferreira de Andrade','breno@rosset.com.br','ROSSET\breno',
        'Tecnologia da Informação','EQP-SIS','PRF-ADMIN','manual',true,true);

INSERT INTO public.expediente (id, dia_semana, minuto_ini, minuto_fim) VALUES
  ('exp-1-m',1,480,720),('exp-1-t',1,840,1080),
  ('exp-2-m',2,480,720),('exp-2-t',2,840,1080),
  ('exp-3-m',3,480,720),('exp-3-t',3,840,1080),
  ('exp-4-m',4,480,720),('exp-4-t',4,840,1080),
  ('exp-5-m',5,480,720),('exp-5-t',5,840,1080);

INSERT INTO public.feriados (id, data_feriado, descricao, recorrente) VALUES
  ('fer-fix-0101', DATE '2026-01-01','Confraternizacao Universal', true),
  ('fer-fix-0421', DATE '2026-04-21','Tiradentes', true),
  ('fer-fix-0501', DATE '2026-05-01','Dia do Trabalho', true),
  ('fer-fix-0907', DATE '2026-09-07','Independencia do Brasil', true),
  ('fer-fix-1012', DATE '2026-10-12','Nossa Senhora Aparecida', true),
  ('fer-fix-1102', DATE '2026-11-02','Finados', true),
  ('fer-fix-1115', DATE '2026-11-15','Proclamacao da Republica', true),
  ('fer-fix-1120', DATE '2026-11-20','Consciencia Negra', true),
  ('fer-fix-1225', DATE '2026-12-25','Natal', true),
  ('fer-2026-carn-seg', DATE '2026-02-16','Carnaval', false),
  ('fer-2026-carn-ter', DATE '2026-02-17','Carnaval', false),
  ('fer-2026-paixao', DATE '2026-04-03','Sexta-feira Santa', false),
  ('fer-2026-corpus', DATE '2026-06-04','Corpus Christi', false);

INSERT INTO public.servicos (id, nome, categoria_id, descricao, tipo_padrao, sla_horas, equipe_id) VALUES
  ('SVC-01','Acesso a sistemas','CAT-SVC-01','Criação, alteração e revogação de acessos a sistemas corporativos.','requisicao',24,'EQP-SDK'),
  ('SVC-02','Estação de trabalho','CAT-SVC-02','Instalação, configuração e manutenção de computadores e periféricos.','requisicao',24,'EQP-SDK'),
  ('SVC-03','Rede e conectividade','CAT-SVC-02','Links, switches, Wi-Fi e conectividade entre unidades.','incidente',8,'EQP-INF'),
  ('SVC-04','Sistemas corporativos','CAT-SVC-03','Suporte funcional e técnico aos sistemas de negócio.','incidente',4,'EQP-SIS'),
  ('SVC-05','E-mail e colaboração','CAT-SVC-03','Caixas postais, listas de distribuição e ferramentas de colaboração.','requisicao',24,'EQP-SDK'),
  ('SVC-06','Relatórios e indicadores','CAT-SVC-03','Extrações, painéis e relatórios gerenciais.','melhoria',72,'EQP-SIS');

INSERT INTO public.sistemas (id, nome, categoria_id, equipe_id, criticidade) VALUES
  ('SYS-01','ERP','CAT-SIS-01','EQP-SIS','alta'),
  ('SYS-02','Portal do Colaborador','CAT-SIS-01','EQP-SDK','media'),
  ('SYS-03','Active Directory','CAT-SIS-02','EQP-INF','alta'),
  ('SYS-04','E-mail corporativo','CAT-SIS-02','EQP-SDK','alta'),
  ('SYS-05','Rede e Wi-Fi','CAT-SIS-02','EQP-INF','alta'),
  ('SYS-06','Estações de trabalho','CAT-SIS-02','EQP-SDK','media');
